//
//  GeometryFighterStyleKit.swift
//  GeometryFighter
//
//  Created by Scott Gardner on 3/24/16.
//  Copyright (c) 2016 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class GeometryFighterStyleKit : NSObject {

    //// Drawing Methods

    public class func drawBackgroundDiffuse(frame frame: CGRect = CGRectMake(0, 0, 120, 120)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let colorOcean = UIColor(red: 0.000, green: 0.251, blue: 0.502, alpha: 1.000)
        var colorOceanHueComponent: CGFloat = 1,
            colorOceanSaturationComponent: CGFloat = 1,
            colorOceanBrightnessComponent: CGFloat = 1
        colorOcean.getHue(&colorOceanHueComponent, saturation: &colorOceanSaturationComponent, brightness: &colorOceanBrightnessComponent, alpha: nil)

        let colorOcean90Brightness = UIColor(hue: colorOceanHueComponent, saturation: colorOceanSaturationComponent, brightness: 0.9, alpha: CGColorGetAlpha(colorOcean.CGColor))

        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [colorOcean90Brightness.CGColor, colorOcean.CGColor], [0, 1])!

        //// Rectangle Drawing
        let rectangleRect = CGRectMake(frame.minX, frame.minY, frame.width, frame.height)
        let rectanglePath = UIBezierPath(rect: rectangleRect)
        CGContextSaveGState(context)
        rectanglePath.addClip()
        let rectangleResizeRatio: CGFloat = min(rectangleRect.width / 120, rectangleRect.height / 120)
        CGContextDrawRadialGradient(context, gradient,
            CGPointMake(rectangleRect.midX + 0 * rectangleResizeRatio, rectangleRect.midY + 0 * rectangleResizeRatio), 0.01 * rectangleResizeRatio,
            CGPointMake(rectangleRect.midX + 0 * rectangleResizeRatio, rectangleRect.midY + 0 * rectangleResizeRatio), 59.99 * rectangleResizeRatio,
            [CGGradientDrawingOptions.DrawsBeforeStartLocation, CGGradientDrawingOptions.DrawsAfterEndLocation])
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfBackgroundDiffuse(frame frame: CGRect = CGRectMake(0, 0, 120, 120)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            GeometryFighterStyleKit.drawBackgroundDiffuse(frame: CGRectMake(0, 0, frame.size.width, frame.size.height))

        let imageOfBackgroundDiffuse = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfBackgroundDiffuse
    }

}
